name: Renovate

on:
  schedule:
    - cron: "0 * * * *"
      timezone: Asia/Shanghai
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: get_token
        with:
          client-id: ${{ vars.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        id: restore
        with:
          path: /tmp/renovate/cache
          key: none
          restore-keys: |
            renovate-

      - run: sudo chown -R 12021:0 /tmp/renovate || true

      - uses: renovatebot/github-action@f66d8679fcfcfa051abde6e7a623007173bf5164 # v46.1.12
        with:
          token: ${{ steps.get_token.outputs.token }}
          configurationFile: config.json
        env:
          LOG_LEVEL: "debug"

      - uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: /tmp/renovate/cache
          key: renovate-${{ github.run_id }}
