name: Renovate

on:
  schedule:
    - cron: "0 * * * *"
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: /tmp/renovate/cache/renovate
          key: renovate

      - uses: renovatebot/github-action@44f24283a60f64273f1294932f16ba61193cccca # v46.1.0
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: config.json
        env:
          LOG_LEVEL: "debug"
